#!/bin/bash

# Prompt the user to enter a number
echo "Enter a number:"
read num

# Initialize sum to 0
sum=0

# Loop to find the sum of digits
while [ $num -gt 0 ]; do
    # Get the last digit
    digit=$((num % 10))
    # Add it to the sum
    sum=$((sum + digit))
    # Remove the last digit
    num=$((num / 10))
done

# Display the result
echo "Sum of digits is: $sum"
